#!/bin/bash

#SBATCH --job-name=hBNhBN             # Name of the job.
#SBATCH --ntasks=nnnnn                # Total number of MPI processes in job.
#SBATCH --nodes=NNNNN                 # Number of nodes in job.
#SBATCH --ntasks-per-node=PPPPP       # Number of MPI processes per node.
#SBATCH --cpus-per-task=8             # Number of OMP threads spawned from each MPI process.
#SBATCH --time=12:00:00               # Max time for your job (hh:mm:ss).
#SBATCH --partition=standard          # Queue. standard CPU nodes with AMD EPYC 7742 64-core processor
#SBATCH --account=e89-warp            # Replace 'e89-soton' with your budget code.
#SBATCH --qos=standard                # Requested Quality of Service (QoS), See ARCHER2 documentation

export OMP_NUM_THREADS=8              # Repeat the value from 'cpus-per-task' here.

# Point this to your ONETEP executable.
onetep_exe=\
"/work/e89/e89/ndmh3/onetep/bin/onetep.archer2_2023_cray"

# Point this to your ONETEP launcher.
onetep_launcher=\
"/work/e89/e89/ndmh3/onetep/utils/onetep_launcher"

# ==========================================================================================================
# !!! You should not need to modify anything below this line.
# ==========================================================================================================

module load PrgEnv-cray/8.3.3
module load cce/15.0.0
module load cray-fftw/3.3.10.3
module load cray-mpich/8.1.23

# These two are crucial to get decent performance of threaded libsci on Archer with the Cray compiler.
export OMP_PLACES=cores
export OMP_PROC_BIND=close

# Uncomment this to get information on affinity/binding in the .err file.
# export CRAY_OMP_CHECK_AFFINITY=TRUE

# This is needed after the Archer2 upgrade or else srun will not know about SLURM's threading settings.
export SRUN_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK

# Works around a memory leak in libfabric on Archer2. Used to be needed in 2022, not sure if needed still.
export FI_MR_CACHE_MAX_COUNT=0

workdir=`pwd`
echo "--- This is the submission script, the time is `date`."
echo "--- ONETEP executable is '$onetep_exe'."
echo "--- workdir is '$workdir'."
echo "--- onetep_launcher is '$onetep_launcher'."

# Ensure exactly 1 .dat file in there.
ndats=`ls -l *dat | wc -l`

if [ "$ndats" == "0" ]; then
  echo "!!! There is no .dat file in the current directory. Aborting." >&2
  touch "%NO_DAT_FILE"
  exit 2
fi

if [ "$ndats" == "1" ]; then
  true
else
  echo "!!! More than one .dat file in the current directory, that's too many. Aborting." >&2
  touch "%MORE_THAN_ONE_DAT_FILE"
  exit 3
fi

rootname=`echo *.dat | sed -r "s/\.dat\$//"`
rootname_dat=$rootname".dat"
rootname_out=$rootname".out"
rootname_err=$rootname".err"

echo "--- The input file is $rootname_dat, the output goes to $rootname_out and errors go to $rootname_err."

# Ensure ONETEP executable is there and is indeed executable.
if [ ! -x "$onetep_exe" ]; then
  echo "!!! $onetep_exe does not exist or is not executable. Aborting!" >&2
  touch "%ONETEP_EXE_MISSING"
  exit 4
fi

# Ensure onetep_launcher is there and is indeed executable.
if [ ! -x "$onetep_launcher" ]; then
  echo "!!! $onetep_launcher does not exist or is not executable. Aborting!" >&2
  touch "%ONETEP_LAUNCHER_MISSING"
  exit 5
fi

# Dump the module list to a file.
module list >\$modules_loaded 2>&1

ldd $onetep_exe >\$ldd

# Report details
echo "--- Number of nodes as reported by SLURM: $SLURM_JOB_NUM_NODES."
echo "--- Number of tasks as reported by SLURM: $SLURM_NTASKS."
echo "--- Using this srun executable: "`which srun`
echo "--- Executing ONETEP via $onetep_launcher."


# Actually run ONETEP
# Additional srun options to pin one thread per physical core
########################################################################################################################################################
srun --hint=nomultithread --distribution=block:block -N $SLURM_JOB_NUM_NODES -n $SLURM_NTASKS $onetep_launcher -e $onetep_exe -t $OMP_NUM_THREADS $rootname_dat >$rootname_out 2>$rootname_err
########################################################################################################################################################

# Check for error conditions
result=$?
echo "--- srun finished at `date`."
if [ $result -ne 0 ]; then
  echo "!!! srun reported a non-zero exit code $result. Aborting!" >&2
  touch "%SRUN_ERROR"
  exit 6
fi

if [ -r $rootname.error_message ]; then
  echo "!!! ONETEP left an error message file. Aborting!" >&2
  touch "%ONETEP_ERROR_DETECTED"
  exit 7
fi

tail $rootname.out | grep completed >/dev/null 2>/dev/null
result=$?
if [ $result -ne 0 ]; then
  echo "!!! ONETEP calculation likely did not complete. Aborting!" >&2
  touch "%ONETEP_DID_NOT_COMPLETE"
  exit 8
fi

echo "--- Looks like everything went fine. Praise be."
touch "%DONE"

echo "--- Finished successfully at `date`."
