#!/bin/bash
#SBATCH --partition=nanosim
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=40
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
##SBATCH --account=phspvr
#SBATCH --job-name=hBN_66_qe

export OMP_NUM_THREADS=1

#module purge; module load GCC/12.3.0  OpenMPI/4.1.5 QuantumESPRESSO/7.2

mpirun -n 40 /storage/nanosim/qe-7.0/bin/pw.x -in hBN_66_qe.scf.in >> hBN_66_qe.scf.out
